export const peptides = [
  { id: 1, name: "Semaglutide", aliases: ["Ozempic", "Wegovy", "Rybelsus"], category: "GLP-1 Agonist", fdaStatus: "FDA Approved", riskLevel: "low", description: "FDA-approved GLP-1 receptor agonist for type 2 diabetes and obesity. Compounding was permitted during shortage but banned after shortage resolution in Oct 2024.", clinicalEvidence: "Extensive Phase 3 human trials. SUSTAIN and STEP trial series. Strong cardiovascular outcome data.", compoundingRules: "Compounding no longer legal at scale after FDA resolved shortage Oct 2024. 503A/503B facilities had until Feb 2025 to cease.", redFlags: ["Weight loss cure claims", "No side effects claims", "Guaranteed results"] },
  { id: 2, name: "Tirzepatide", aliases: ["Mounjaro", "Zepbound"], category: "GLP-1/GIP Dual Agonist", fdaStatus: "FDA Approved", riskLevel: "low", description: "FDA-approved dual GLP-1/GIP receptor agonist for type 2 diabetes and obesity. Shortage resolved May 2024 with a 60-day wind-down period.", clinicalEvidence: "SURPASS and SURMOUNT trial series. Superior weight loss vs semaglutide in head-to-head trials.", compoundingRules: "Compounding permitted during shortage. 60-day wind-down began Mar 2024, ended May 2024. Compounding now prohibited.", redFlags: ["Better than Ozempic claims without evidence", "Compounded versions still advertised as legal"] },
  { id: 3, name: "Tesamorelin", aliases: ["Egrifta"], category: "GHRH Analog", fdaStatus: "FDA Approved", riskLevel: "low", description: "FDA-approved growth hormone-releasing hormone analog for HIV-associated lipodystrophy. Only legal use is for this specific indication.", clinicalEvidence: "Phase 3 trials in HIV patients. Evidence outside this indication is limited.", compoundingRules: "503A compounding permitted for specific patient needs. Off-label use for anti-aging or performance is not FDA-sanctioned.", redFlags: ["Anti-aging claims", "Muscle building claims", "Fat loss for general population"] },
  { id: 4, name: "Bremelanotide", aliases: ["PT-141", "Vyleesi"], category: "Melanocortin Receptor Agonist", fdaStatus: "FDA Approved", riskLevel: "medium", description: "FDA-approved for hypoactive sexual desire disorder in premenopausal women. Gray market versions sold as PT-141 are unregulated.", clinicalEvidence: "Phase 3 trials for HSDD. Gray market peptide versions lack quality control.", compoundingRules: "Compounded PT-141 is legally gray. FDA-approved Vyleesi is the only sanctioned form.", redFlags: ["Libido enhancement for men", "Performance enhancement claims", "No prescription needed"] },
  { id: 5, name: "SS-31 (Elamipretide)", aliases: ["FORZINITY", "MTP-131"], category: "Mitochondria-Targeting Peptide", fdaStatus: "FDA Approved", riskLevel: "low", description: "Received FDA accelerated approval Sep 2024 for Barth syndrome. Only the 4th peptide drug with FDA approval.", clinicalEvidence: "Phase 3 TAZPOWER trial in Barth syndrome patients. Accelerated approval based on functional outcomes.", compoundingRules: "Only approved for Barth syndrome. Off-label compounding for other uses is not sanctioned.", redFlags: ["Anti-aging mitochondrial claims", "General energy enhancement claims"] },
  { id: 6, name: "BPC-157", aliases: ["Body Protection Compound 157", "PL 14736"], category: "Synthetic Peptide", fdaStatus: "Not Approved", riskLevel: "high", description: "Added to FDA 503A/503B Category 2 banned bulk substances list Oct 2023. All human healing claims extrapolate from rodent studies only.", clinicalEvidence: "Zero completed human Phase 1/2/3 trials as of 2026. All evidence is from rodent studies by one Croatian research group.", compoundingRules: "BANNED. Cannot be compounded legally in 503A or 503B facilities in the US since Oct 2023.", redFlags: ["Gut healing claims", "Tendon repair claims", "Injury recovery", "Research Use Only loophole claims"] },
  { id: 7, name: "CJC-1295", aliases: ["CJC-1295 DAC", "Drug Affinity Complex"], category: "GHRH Analog", fdaStatus: "Not Approved", riskLevel: "high", description: "Added to FDA 503A/503B banned list Oct 2023. PCAC voted against inclusion on 503A permitted list in Dec 2023.", clinicalEvidence: "No completed human clinical trials. Animal data only.", compoundingRules: "BANNED from 503A/503B compounding since Oct 2023.", redFlags: ["HGH alternative claims", "Anti-aging", "Muscle growth", "Fat loss"] },
  { id: 8, name: "Ipamorelin", aliases: ["IPAM"], category: "Ghrelin Mimetic / GH Secretagogue", fdaStatus: "Not Approved", riskLevel: "high", description: "Added to FDA 503A/503B banned list Oct 2023 alongside CJC-1295. PCAC voted against it in Dec 2023.", clinicalEvidence: "Limited human data. No FDA-sanctioned trials completed.", compoundingRules: "BANNED from 503A/503B compounding since Oct 2023.", redFlags: ["Growth hormone booster claims", "Sleep improvement", "Anti-aging stacks"] },
  { id: 9, name: "TB-500", aliases: ["Thymosin Beta-4"], category: "Thymic Peptide", fdaStatus: "Not Approved", riskLevel: "high", description: "Added to FDA banned bulk substances list Oct 2023. Independent lab testing found endotoxins in TB-500 vials.", clinicalEvidence: "No completed human trials. Animal wound healing data only.", compoundingRules: "BANNED from 503A/503B compounding since Oct 2023.", redFlags: ["Healing acceleration", "Recovery claims", "Injury repair", "Veterinary grade sold for human use"] },
  { id: 10, name: "Melanotan II", aliases: ["MT-2", "MT-II"], category: "Melanocortin Receptor Agonist", fdaStatus: "Not Approved", riskLevel: "critical", description: "Multiple international agencies including FDA, MHRA, and TGA have issued bans after documented melanoma activation, priapism, and contaminated product deaths.", clinicalEvidence: "Documented adverse events including death. No approved human use anywhere.", compoundingRules: "Illegal. Cannot be compounded or sold for human use.", redFlags: ["Tanning peptide", "Libido enhancement", "Barbie drug", "No side effects claims"] },
  { id: 11, name: "Ibutamoren", aliases: ["MK-677", "Nutrobal"], category: "GH Secretagogue", fdaStatus: "Not Approved", riskLevel: "high", description: "Non-peptide GH secretagogue. Not FDA approved. Often sold alongside peptides in gray market. Associated with water retention, insulin resistance, and potential cancer risk.", clinicalEvidence: "Some human pharmacokinetic data but no approved indication. Long-term safety unknown.", compoundingRules: "Cannot be legally compounded. Classified as investigational.", redFlags: ["HGH replacement", "Muscle building without steroids", "Anti-aging", "Sold as supplement"] },
  { id: 12, name: "AOD-9604", aliases: ["Anti-Obesity Drug 9604"], category: "GH Fragment", fdaStatus: "Not Approved", riskLevel: "high", description: "GH fragment. PCAC voted against inclusion on 503A permitted list Dec 2023. No FDA-approved use.", clinicalEvidence: "Failed Phase 3 trials for obesity. No approved indication.", compoundingRules: "BANNED from 503A/503B compounding. PCAC rejected it Dec 2023.", redFlags: ["Fat burning claims", "Lipolysis", "GH fragment safer than HGH claims"] }
];

export const enforcementActions = [
  { id: 1, date: "March 2026", agency: "FDA/FTC", company: "30+ Telehealth Companies", violation: "GLP-1 Marketing Violations", description: "FDA and FTC issued simultaneous enforcement notices to 30+ telehealth companies for misleading GLP-1 compounding marketing.", status: "Active", compound: "Semaglutide/Tirzepatide" },
  { id: 2, date: "February 2025", agency: "FDA", company: "All 503A/503B Facilities", violation: "Illegal Semaglutide Compounding", description: "FDA enforcement deadline: all 503A/503B facilities required to cease semaglutide compounding following shortage resolution.", status: "Resolved", compound: "Semaglutide" },
  { id: 3, date: "October 2024", agency: "FDA", company: "Compounding Pharmacies", violation: "Post-Shortage Compounding", description: "FDA resolved semaglutide shortage making large-scale compounding no longer legal.", status: "Resolved", compound: "Semaglutide" },
  { id: 4, date: "October 2023", agency: "FDA", company: "503A/503B Facilities", violation: "Banned Bulk Substance Compounding", description: "FDA added BPC-157, CJC-1295, Ipamorelin, TB-500, and 14 other compounds to the 503A/503B Category 2 banned bulk substances list.", status: "Ongoing", compound: "BPC-157, CJC-1295, Ipamorelin, TB-500" },
  { id: 5, date: "2023", agency: "FDA/MHRA/TGA", company: "Multiple Gray Market Vendors", violation: "Dangerous Unregulated Product Sales", description: "International coordinated action against Melanotan II vendors following documented deaths and melanoma activation cases.", status: "Ongoing", compound: "Melanotan II" },
  { id: 6, date: "March 2024", agency: "FDA", company: "Compounding Pharmacies", violation: "Tirzepatide Post-Shortage Compounding", description: "Tirzepatide shortage declared resolved. 60-day wind-down period began for compounders, ending May 2024.", status: "Resolved", compound: "Tirzepatide" }
];

export const redFlagClaims = [
  { id: 1, claim: "Heals leaky gut naturally", compound: "BPC-157", riskLevel: "critical", reason: "BPC-157 is banned for compounding. No human trials support gut healing claims." },
  { id: 2, claim: "Legal Research Use Only (RUO) peptides", compound: "Multiple", riskLevel: "critical", reason: "FDA has held RUO labels do not exempt products from drug regulations when sold with dosing instructions." },
  { id: 3, claim: "Natural HGH booster", compound: "CJC-1295/Ipamorelin", riskLevel: "high", reason: "Both compounds are banned from compounding since Oct 2023. HGH claims are unsubstantiated." },
  { id: 4, claim: "Repairs tendons and injuries faster", compound: "BPC-157/TB-500", riskLevel: "high", reason: "All injury repair evidence comes from rodent studies. Both compounds are banned for human compounding." },
  { id: 5, claim: "Tanning peptide no UV needed", compound: "Melanotan II", riskLevel: "critical", reason: "Melanotan II has caused documented deaths and melanoma activation. Banned internationally." },
  { id: 6, claim: "Compounded semaglutide still available legally", compound: "Semaglutide", riskLevel: "high", reason: "Large-scale compounding illegal after Oct 2024 shortage resolution." },
  { id: 7, claim: "MK-677 is a legal supplement", compound: "Ibutamoren", riskLevel: "high", reason: "Ibutamoren is an investigational drug, not a supplement. Cannot be legally sold as such." },
  { id: 8, claim: "No side effects unlike HGH", compound: "CJC-1295/Ipamorelin", riskLevel: "high", reason: "No long-term human safety data. Both banned from compounding." },
  { id: 9, claim: "FDA approved peptide therapy", compound: "Multiple", riskLevel: "critical", reason: "Only 4 peptides are FDA approved. Most peptides marketed online are not." },
  { id: 10, claim: "30 years of research proves BPC-157 works", compound: "BPC-157", riskLevel: "high", reason: "All 30 years of research is from rat studies by one Croatian lab. Zero human trials completed." }
];

export const regulatoryTimeline = [
  { date: "Aug 2022", color: "blue", text: "Semaglutide added to FDA shortage list, compounding permitted" },
  { date: "Oct 2023", color: "red", text: "FDA adds BPC-157, CJC-1295, Ipamorelin, TB-500 and 14 others to 503A/503B banned list" },
  { date: "Dec 2023", color: "red", text: "PCAC votes AGAINST CJC-1295, Ipamorelin, AOD-9604 for inclusion on 503A permitted list" },
  { date: "Mar 2024", color: "yellow", text: "Tirzepatide shortage resolved, 60-day wind-down begins, ends May 2024" },
  { date: "Sep 2024", color: "green", text: "SS-31 (Elamipretide / FORZINITY) receives FDA accelerated approval for Barth syndrome" },
  { date: "Oct 2024", color: "red", text: "FDA resolves semaglutide shortage, compounding at scale no longer legal" },
  { date: "Feb 2025", color: "red", text: "FDA deadline: all 503A/503B facilities must cease semaglutide compounding" },
  { date: "Mar 2026", color: "orange", text: "FDA/FTC joint sweep: 30 telehealth companies receive enforcement notices for GLP-1 marketing violations" }
];

export const keyIntelligence = [
  { icon: "shield", color: "green", title: "Only 4 peptide drugs are FDA approved", body: "Semaglutide, Tirzepatide, Tesamorelin, Bremelanotide, and SS-31. Everything else is investigational, gray market, or banned." },
  { icon: "warning", color: "yellow", title: "The Research Use Only label is a legal fiction", body: "FDA has consistently held that RUO labels do not exempt products from drug regulations when sold with human dosing instructions." },
  { icon: "danger", color: "red", title: "Melanotan II has caused deaths", body: "Multiple international agencies including FDA, MHRA, and TGA have issued bans after documented melanoma activation and contaminated product deaths." },
  { icon: "info", color: "blue", title: "BPC-157 30 years of research equals rat studies only", body: "Every human healing claim for BPC-157 extrapolates from rodent data by one Croatian research group. Zero completed human trials exist as of 2026." },
  { icon: "warning", color: "orange", title: "Gray market contamination is documented", body: "Independent lab testing found lead in BPC-157 samples, endotoxins in TB-500 vials, and CJC-1295 dosed at less than 42% of stated potency." }
];
